version: 2
jobs:
  plan-apply:
    working_directory: /data-infrastructure/data-products/data-product-a
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:0.13.7
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            echo ${GCP_CREDENTIALS} | base64 -d account.json
            # terraform init -input=false
            # terraform plan -out tfapply -var-file env/dev.tfvars
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply